# #####################################################################
# Docker Compose para o Ambiente de Desenvolvimento Local do AxonAI
# #####################################################################
# Este arquivo define e orquestra os serviços necessários para rodar
# a aplicação AxonAI localmente: o backend e o banco de dados.
#
# Comando para executar: docker-compose up --build
# Comando para parar: docker-compose down
# #####################################################################

services:
  # --- Serviço do Banco de Dados PostgreSQL ---
  db:
    image: postgres:16-alpine
    container_name: axonal-db-local
    # CORREÇÃO: O caminho para o .env agora aponta para dentro da pasta 'backend'.
    env_file:
      - ./backend/.env
    volumes:
      - axonal-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- Serviço da Aplicação Backend ---
  backend:
    container_name: axonal-backend-local
    build:
      # CORREÇÃO: O contexto de build do Docker agora é o diretório './backend'.
      context: ./backend
    # CORREÇÃO: O caminho para o .env agora aponta para dentro da pasta 'backend'.
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    environment:
      # Esta sobrescrita continua correta e necessária.
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/axonaldb
    depends_on:
      db:
        condition: service_healthy

volumes:
  axonal-db-data: