services:
  db:
    image: postgres:16-alpine
    container_name: axonal-db-local
    # O Docker Compose lê o .env do backend e passa as variáveis para este container.
    env_file:
      - ./backend/.env
    volumes:
      - axonal-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d axonaldb"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: axonal-backend-local
    build:
      context: ./backend
    # Passa o arquivo .env para dentro do container do backend.
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    # A configuração do datasource agora é feita pelo Spring Profile, mas
    # precisamos sobrescrever a URL para usar o hostname da rede Docker.
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/axonaldb
    depends_on:
      db:
        condition: service_healthy

volumes:
  axonal-db-data: