
services:
  - name: axonal-ui-staging
    type: static
    plan: starter
    rootDir: ./frontend
    buildCommand: npm install && npm run build
    publishDir: dist
    autoDeploy: true
    branch: main
    routes:
      - type: rewrite
        source: /*
        destination: /index.html