databases:
  - name: axonal-db-staging
    plan: free # ALTERADO: "starter" para "free" para usar o nível gratuito.

services:
  - name: axonal-api-staging
    type: web
    plan: free # ALTERADO: "starter" para "free" para usar o nível gratuito.
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    autoDeploy: true
    branch: main
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: staging
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: axonal-db-staging
          property: connectionString
  - name: axonal-ui-staging
    type: web
    runtime: static
    plan: free # ALTERADO: "starter" para "free" para usar o nível gratuito.
    rootDir: ./frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    autoDeploy: true
    branch: main
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

