services:
  - name: axonal-db-staging
    type: pserv
    runtime: postgres
    plan: starter
  - name: axonal-api-staging
    type: web
    plan: starter
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    autoDeploy: true
    branch: main
    healthCheck:
      path: /actuator/health
      initialDelaySeconds: 120
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: staging
      - key: SPRING_DATASOURCE_URL
        fromService:
          type: pserv
          name: axonal-db-staging
          property: connectionString
  - name: axonal-ui-staging
    type: static site
    env: static # ADICIONADO: Propriedade presente no exemplo da documentação.
    plan: starter
    rootDir: ./frontend
    buildCommand: npm install && npm run build
    publishDir: dist
    autoDeploy: true
    branch: main
    routes:
      - type: rewrite
        source: /*
        destination: /index.html