services:
  - name: axonal-db-staging
    type: pserv
    runtime: postgres
    plan: starter
  - name: axonal-api-staging
    type: web
    plan: starter
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    autoDeploy: true
    branch: main
    healthCheckPath: /actuator/health 
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: staging
      - key: SPRING_DATASOURCE_URL
        fromService:
          type: pserv
          name: axonal-db-staging
          property: connectionString
  - name: axonal-ui-staging
    type: web
    runtime: static
    plan: starter
    rootDir: ./frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    autoDeploy: true
    branch: main
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

