# render.yaml - Blueprint de Infraestrutura como Código para o AxonAI
services:
  # --- Serviço do Banco de Dados PostgreSQL ---
  - name: axonal-db-staging
    type: pserv # pserv significa "Private Service", não acessível pela internet
    plan: free # Para começar; pode ser atualizado para 'starter' para mais recursos

  # --- Serviço da Aplicação Backend ---
  - name: axonal-api-staging
    type: web # web significa que terá um URL público
    plan: free
    runtime: docker
    
    # Aponta para o Dockerfile do nosso backend, relativo à raiz do repositório
    dockerfilePath: ./backend/Dockerfile
    
    # Variáveis de Ambiente e Segredos
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: staging # Ativa o perfil de staging do Spring Boot para futuras configurações
      
      # Injeta automaticamente as variáveis de conexão a partir do serviço de BD
      - fromService:
          type: pserv
          name: axonal-db-staging
          # Mapeia os nomes das variáveis do Render para os nomes que o Spring espera
          envVarMappings:
            - from: user
              to: SPRING_DATASOURCE_USERNAME
            - from: password
              to: SPRING_DATASOURCE_PASSWORD
            - from: host
              to: DB_HOST # Usamos variáveis temporárias para construir a URL
            - from: database
              to: DB_NAME
              
      # Constrói a URL JDBC final que o Spring irá usar, com base nas variáveis injetadas
      - key: SPRING_DATASOURCE_URL
        value: "jdbc:postgresql://${DB_HOST}/${DB_NAME}"