databases: 
  - name: axonal-db-staging
    plan: starter

services:
  - name: axonal-api-staging
    type: web
    plan: starter
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    autoDeploy: true
    branch: main
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: staging
      - key: SPRING_DATASOURCE_URL
        fromDatabase: # CORREÇÃO: A referência deve ser "fromDatabase".
          name: axonal-db-staging
          property: connectionString
  - name: axonal-ui-staging
    type: web
    runtime: static
    plan: starter
    rootDir: ./frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    autoDeploy: true
    branch: main
    routes:
      - type: rewrite
        source: /*
        destination: /index.html