databases:
  - name: axonal-db-staging
    plan: free

services:
  - name: axonal-api-staging
    type: web
    plan: free
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    autoDeploy: true
    branch: main
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: staging
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: axonal-db-staging
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: axonal-db-staging
          property: password
      - key: SPRING_DATASOURCE_HOST
        fromDatabase:
          name: axonal-db-staging
          property: host
      - key: SPRING_DATASOURCE_PORT
        fromDatabase:
          name: axonal-db-staging
          property: port
      - key: SPRING_DATASOURCE_DB_NAME
        fromDatabase:
          name: axonal-db-staging
          property: database
  - name: axonal-ui-staging
    type: web
    runtime: static
    rootDir: ./frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    autoDeploy: true
    branch: main
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

