# Configurações para o ambiente de desenvolvimento (dev)
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/axonaldb
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate