spring:
  datasource:
    # Nota: usamos localhost aqui para quando rodamos a app via IDE.
    # O Docker Compose irá sobrescrever esta URL.
    url: jdbc:postgresql://localhost:5432/axonaldb
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      # 'validate' instrui o Hibernate a verificar se o esquema da base de dados
      # corresponde às entidades da aplicação no arranque, sem fazer alterações.
      # É uma configuração segura para ambientes de produção e staging.
      ddl-auto: validate
    # ADICIONADO: Define explicitamente o dialeto do PostgreSQL para o Hibernate.
    # Isto remove a necessidade de auto-detecção, que pode ser falível em ambientes de cloud.
    database-platform: org.hibernate.dialect.PostgreSQLDialect

